### ISSUE TITLE
error on deploy to Heroku

### ISSUE THREAD

**Issue by andyras** [TeachTechTaskForce/edumap#116]
The app runs fine locally but something goes wrong when running `rake assets:precompile` during heroku 

### possibly useful articles/threads:
* https://devcenter.heroku.com/articles/rails-asset-pipeline
* http://stackoverflow.com/questions/24415269/heroku-rejects-my-git-push-request

Full output of deploy attempt:
```
>> git subtree push --prefix edumap heroku master
git push using:  heroku master
Counting objects: 279, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (271/271), done.
Writing objects: 100% (279/279), 26.40 KiB | 0 bytes/s, done.
Total 279 (delta 197), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Using set buildpack heroku/ruby
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.2.4
remote: ###### WARNING:
remote:        Removing `Gemfile.lock` because it was generated on Windows.
remote:        Bundler will do a full resolve so native gems are handled properly.
remote:        This may result in unexpected gem versions being used in your app.
remote:        In rare occasions Bundler may not be able to resolve your dependencies at all.
remote:        https://devcenter.heroku.com/articles/bundler-windows-gemfile
remote: 
remote: -----> Installing dependencies using bundler 1.11.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4
remote:        Fetching gem metadata from https://rubygems.org/...........
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Resolving dependencies..............
remote:        Using i18n 0.7.0
remote:        Using json 1.8.3
remote:        Using minitest 5.9.0
remote:        Using thread_safe 0.3.5
remote:        Using builder 3.2.2
remote:        Using erubis 2.7.0
remote:        Installing pkg-config 1.1.7
remote:        Using rack 1.6.4
remote:        Installing rake 11.2.2
remote:        Installing mini_portile2 2.1.0
remote:        Using arel 6.0.3
remote:        Using thor 0.19.1
remote:        Using sass 3.4.22
remote:        Using bundler 1.11.2
remote:        Using concurrent-ruby 1.0.2
remote:        Installing mime-types-data 3.2016.0521
remote:        Using coffee-script-source 1.10.0
remote:        Using daemons 1.2.3
remote:        Using eventmachine 1.2.0.1
remote:        Using sexp_processor 4.7.0
remote:        Installing execjs 2.7.0
remote:        Installing tilt 2.0.5
remote:        Using pg 0.18.4
remote:        Using will_paginate 3.1.0
remote:        Using rdoc 4.2.2
remote:        Using sendgrid 1.2.4
remote:        Using tzinfo 1.2.2
remote:        Using rack-test 0.6.3
remote:        Installing multi_json 1.12.1
remote:        Installing turbolinks-source 5.0.0
remote:        Installing nokogiri 1.6.8 with native extensions
remote:        Installing sprockets 3.6.3
remote:        Installing mime-types 3.1
remote:        Using ruby_parser 3.8.2
remote:        Installing thin 1.7.0 with native extensions
remote:        Installing autoprefixer-rails 6.3.7
remote:        Using coffee-script 2.4.1
remote:        Using uglifier 3.0.0
remote:        Using haml 4.0.7
remote:        Using will_paginate-bootstrap 1.0.1
remote:        Using sdoc 0.4.1
remote:        Using activesupport 4.2.4
remote:        Installing turbolinks 5.0.0
remote:        Using mail 2.6.4
remote:        Using bootstrap-sass 3.3.6
remote:        Using rails-deprecated_sanitizer 1.0.3
remote:        Using globalid 0.3.6
remote:        Using activemodel 4.2.4
remote:        Installing jbuilder 2.5.0
remote:        Using activejob 4.2.4
remote:        Using activerecord 4.2.4
remote:        Using rails-dom-testing 1.0.7
remote:        Using loofah 2.0.3
remote:        Using html2haml 2.0.0
remote:        Using rails-html-sanitizer 1.0.3
remote:        Using actionview 4.2.4
remote:        Using actionpack 4.2.4
remote:        Using actionmailer 4.2.4
remote:        Using railties 4.2.4
remote:        Using simple_form 3.2.1
remote:        Using bootstrap-datepicker-rails 1.6.1.1
remote:        Using coffee-rails 4.1.1
remote:        Using haml-rails 0.9.0
remote:        Using jquery-rails 4.1.1
remote:        Installing sprockets-rails 3.1.1
remote:        Using rails 4.2.4
remote:        Using filterrific 2.0.5
remote:        Installing sass-rails 5.0.5
remote:        Using chardinjs-rails 0.1.3
remote:        Installing js-routes 1.2.6
remote:        Bundle complete! 32 Gemfile dependencies, 70 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (15.32s)
remote:        Cleaning up the bundler cache.
remote:        Removing sprockets (3.6.0)
remote:        Removing autoprefixer-rails (6.3.6.1)
remote:        Removing sass-rails (5.0.4)
remote:        Removing execjs (2.6.0)
remote:        Removing thin (1.6.4)
remote:        Removing rake (11.1.2)
remote:        Removing nokogiri (1.6.7.2)
remote:        Removing turbolinks (2.5.3)
remote:        Removing js-routes (1.2.5)
remote:        Removing mime-types (3.0)
remote:        Removing multi_json (1.12.0)
remote:        Removing mime-types-data (3.2016.0221)
remote:        Removing tilt (2.0.4)
remote:        Removing jbuilder (2.4.1)
remote:        Removing sprockets-rails (3.0.4)
remote:        Removing mini_portile2 (2.0.0)
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        W, [2016-07-05T22:22:06.965955 #672]  WARN -- : Warning: SENDGRID_USERNAME, SENDGRID_PASSWORD and CONTACT_TO environment variables must all be set for the contact form to work. Contact emails will appear in the logs but will not be sent.
remote:        rake aborted!
remote:        ExecJS::ProgramError: Unexpected token: name (handleTableClass) (line: 16657, col: 4, pos: 503010)
remote:        Error
remote:        at new JS_Parse_Error (/tmp/execjs20160705-672-1innr35js:3572:11870)
remote:        at js_error (/tmp/execjs20160705-672-1innr35js:3572:12089)
remote:        at croak (/tmp/execjs20160705-672-1innr35js:3572:20898)
remote:        at token_error (/tmp/execjs20160705-672-1innr35js:3572:21035)
remote:        at unexpected (/tmp/execjs20160705-672-1innr35js:3572:21123)
remote:        at semicolon (/tmp/execjs20160705-672-1innr35js:3572:21615)
remote:        at simple_statement (/tmp/execjs20160705-672-1innr35js:3572:24478)
remote:        at /tmp/execjs20160705-672-1innr35js:3572:22447
remote:        at /tmp/execjs20160705-672-1innr35js:3572:21788
remote:        at /tmp/execjs20160705-672-1innr35js:3573:2092
remote:        at Object.parse (/tmp/execjs20160705-672-1innr35js:3573:2301)
remote:        at parse (/tmp/execjs20160705-672-1innr35js:3903:22)
remote:        new JS_Parse_Error ((execjs):3572:11870)
remote:        js_error ((execjs):3572:12089)
remote:        croak ((execjs):3572:20898)
remote:        token_error ((execjs):3572:21035)
remote:        unexpected ((execjs):3572:21123)
remote:        semicolon ((execjs):3572:21615)
remote:        simple_statement ((execjs):3572:24478)
remote:        (execjs):3572:22447
remote:        (execjs):3572:21788
remote:        (execjs):3573:2092
remote:        Object.parse ((execjs):3573:2301)
remote:        parse ((execjs):3903:22)
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:21:in `eval'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:46:in `call'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/uglifier-3.0.0/lib/uglifier.rb:176:in `run_uglifyjs'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/uglifier-3.0.0/lib/uglifier.rb:139:in `compile'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/uglifier_compressor.rb:52:in `call'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/uglifier_compressor.rb:28:in `call'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/processor_utils.rb:75:in `call_processor'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/processor_utils.rb:56:in `reverse_each'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/processor_utils.rb:56:in `call_processors'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/loader.rb:134:in `load_from_unloaded'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/loader.rb:60:in `block in load'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/loader.rb:44:in `load'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/cached_environment.rb:47:in `yield'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/cached_environment.rb:47:in `load'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/base.rb:66:in `find_asset'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/base.rb:73:in `find_all_linked_assets'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/manifest.rb:142:in `block in find'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/path_utils.rb:209:in `each'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/path_utils.rb:209:in `stat_directory'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/path_utils.rb:227:in `stat_tree'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/legacy.rb:105:in `each'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/legacy.rb:105:in `block in logical_paths'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/legacy.rb:104:in `each'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/legacy.rb:104:in `logical_paths'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/manifest.rb:140:in `find'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/sprockets/manifest.rb:185:in `compile'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.1.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.3/lib/rake/sprocketstask.rb:147:in `with_logger'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.1.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
remote:        /tmp/build_e93008693b32bb9ef82218c46056ff00/vendor/bundle/ruby/2.2.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to limitless-retreat-77466.
remote: 
To https://git.heroku.com/limitless-retreat-77466.git
 ! [remote rejected] bfa02a5c0bd834c58a9962cdbfd8dc20eb582207 -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/limitless-retreat-77466.git'
```

**Comment by andyras** [comment]
I actually got past this issue by following the advice in the SO thread, but now upon deployment I get the following in the logs:

```
2016-07-05T22:22:08.163229+00:00 heroku[slug-compiler]: Slug compilation failed: failed to compile Ruby app
2016-07-05T22:29:23.598506+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 40376 -e production`
2016-07-05T22:29:19.550500+00:00 heroku[api]: Deploy d9fa3f9 by andyras@gmail.com
2016-07-05T22:29:19.550685+00:00 heroku[api]: Release v6 created by andyras@gmail.com
2016-07-05T22:30:47.781317+00:00 heroku[router]: at=info method=GET path="/" host=limitless-retreat-77466.herokuapp.com request_id=4ebd5be8-ca0f-4de5-9f6c-4d259295692f fwd="64.150.11.40" dyno=web.1 connect=0ms service=59ms status=500 bytes=1683
2016-07-05T22:32:15.106952+00:00 heroku[router]: at=info method=GET path="/" host=limitless-retreat-77466.herokuapp.com request_id=5419fc77-5bcd-484f-ae66-bb6ba71732b9 fwd="64.150.11.40" dyno=web.1 connect=1ms service=23ms status=500 bytes=1683
```

**Comment by pjsier** [comment]
Are the Sendgrid configuration variables set in Heroku? That looks like the
issue, and if they're not that's a quick fix

**Comment by andyras** [comment]
Looks like they are not. How would I go about setting that up/where should I look for the correct values?

<img width="818" alt="screen shot 2016-07-05 at 17 47 34" src="https://cloud.githubusercontent.com/assets/1231749/16602302/9aee2e36-42d8-11e6-8025-b12bd25a2ad6.png">
